server:
  port: 8777
kal: this is the val
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_mp?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&rewriteBatchedStatements=true
    #    url: jdbc:mysql://localhost:3306/learn_mp?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&rewriteBatchedStatement
    username: root
    password: root
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#jpa:
#  hibernate:
#    ddl-auto: update
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect  # 使用 MySQL8Dialect
#      format_sql: true  # 格式化 SQL
#  show-sql: true  # 显示 SQL

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml  # 如果有使用 XML 文件
  type-aliases-package: org.example.pojo.entity  # 设置实体类别名的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台输出 SQL 语句
    cache-enabled: true #开启二级缓存
    map-underscore-to-camel-case: true #是否开启下划线和驼峰映射
    lazy-loading-enabled: true #开启懒加载
    aggressive-lazy-loading: true #全部属性开启懒加载
  global-config: # 全局配置
    banner: true #开启mybatis logo
    db-config:
      id-type: assign_id #id默认为雪花ID
      update-strategy: not_null #更新策略,只更新非空字段
      table-prefix: t_
      logic-delete-field: delFlag #全局逻辑删除的实体字段名,字段类型可以是boolean,integer 可以更加灵活一些,用@TableLogic 进行字段标注
      logic-delete-value: 0 #逻辑已删除(默认为1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为0)


logging:
  level:
    root: INFO  # 根日志级别
    com.baomidou.mybatisplus: DEBUG  # 打印 MyBatis-Plus 的 SQL 语句
    org.apache.ibatis: DEBUG  # 打印 MyBatis 的 SQL 语句
    org.hibernate.SQL: DEBUG  # 如果使用 Hibernate，打印 Hibernate 执行的 SQL 语句
    com.example: DEBUG
