server:
  port: 8777
kal: this is the val
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_mp?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    username: root
    password: root
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#jpa:
#  hibernate:
#    ddl-auto: update
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect  # 使用 MySQL8Dialect
#      format_sql: true  # 格式化 SQL
#  show-sql: true  # 显示 SQL

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml  # 如果有使用 XML 文件
  type-aliases-package: org.example.dao.*  # 设置实体类别名的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台输出 SQL 语句
  global-config:
    db-config:
      sql-in-xml: true  # 允许在 XML 中使用 SQL

logging:
  level:
    root: INFO  # 根日志级别
    com.baomidou.mybatisplus: DEBUG  # 打印 MyBatis-Plus 的 SQL 语句
    org.apache.ibatis: DEBUG  # 打印 MyBatis 的 SQL 语句
    org.hibernate.SQL: DEBUG  # 如果使用 Hibernate，打印 Hibernate 执行的 SQL 语句
    com.example: DEBUG
